# **PyTorch NN Module**
---

## **Importing Necessary Libraries, Modules and Packages**

In [154]:
import torch
import torch.nn as nn

In [155]:
# Creating dataset
features = torch.rand(10,5)
features

tensor([[0.8604, 0.8277, 0.1970, 0.9180, 0.3698],
        [0.2826, 0.5250, 0.7619, 0.1721, 0.0814],
        [0.2152, 0.5575, 0.2615, 0.9093, 0.7837],
        [0.1936, 0.3862, 0.8869, 0.2327, 0.0743],
        [0.7974, 0.8802, 0.1557, 0.5482, 0.4817],
        [0.7505, 0.8711, 0.5069, 0.3931, 0.1852],
        [0.6512, 0.7511, 0.1650, 0.9805, 0.9063],
        [0.2488, 0.1049, 0.2596, 0.5677, 0.1873],
        [0.2956, 0.7832, 0.5526, 0.0501, 0.7602],
        [0.4419, 0.2609, 0.7608, 0.1837, 0.5731]])

---

## **Version 1**

In [156]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [157]:
# Creating model
model = Model(features.shape[1])

# Forward Pass
model.forward(features)

tensor([[0.3424],
        [0.4073],
        [0.3477],
        [0.4025],
        [0.3641],
        [0.3724],
        [0.3183],
        [0.4197],
        [0.3783],
        [0.3731]], grad_fn=<SigmoidBackward0>)

In [158]:
# Showing model weights
model.linear.weight

Parameter containing:
tensor([[-0.1967, -0.1029, -0.2894, -0.2898, -0.2778]], requires_grad=True)

In [159]:
# Showing model bias
model.linear.bias

Parameter containing:
tensor([0.0275], requires_grad=True)

In [160]:
# Visualize
!pip install torchinfo

In [161]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

---

## **Version 2**

In [162]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        # Layer 1
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()

        # Layer 2
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        # Layer 1
        out = self.linear1(features)
        out = self.relu(out)

        # Layer 2
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [163]:
# Creating model
model = Model(features.shape[1])

# Forward Pass
model.forward(features)

tensor([[0.6250],
        [0.6316],
        [0.6356],
        [0.6381],
        [0.6153],
        [0.6219],
        [0.6277],
        [0.6309],
        [0.6201],
        [0.6300]], grad_fn=<SigmoidBackward0>)

In [164]:
# Showing model weights
model.linear1.weight

Parameter containing:
tensor([[-0.3598, -0.3438,  0.4285, -0.2271, -0.3032],
        [-0.1038, -0.1033,  0.2340,  0.2333, -0.0690],
        [-0.2794,  0.1256,  0.3635,  0.2990,  0.1562]], requires_grad=True)

In [165]:
# Showing model bias
model.linear1.bias

Parameter containing:
tensor([-0.1939,  0.3057,  0.0424], requires_grad=True)

In [166]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

---

## **Version 3**

In [167]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(num_features, 3), # index 0
            nn.ReLU(), # index 1
            nn.Linear(3,1), # index 2
            nn.Sigmoid() # index 3
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [168]:
# Creating model
model = Model(features.shape[1])

# Forward Pass
model.forward(features)

tensor([[0.6187],
        [0.6169],
        [0.6089],
        [0.6206],
        [0.6099],
        [0.6159],
        [0.6118],
        [0.6193],
        [0.6068],
        [0.6170]], grad_fn=<SigmoidBackward0>)

In [169]:
# Showing model weights
model.network[0].weight

Parameter containing:
tensor([[ 0.1573, -0.1856,  0.2063,  0.2019, -0.1533],
        [-0.2831, -0.3164,  0.2149,  0.2273,  0.1416],
        [ 0.3995,  0.1434, -0.0919, -0.3496,  0.0984]], requires_grad=True)

In [170]:
model.network[2].weight

Parameter containing:
tensor([[ 0.3084, -0.3645, -0.3110]], requires_grad=True)

In [171]:
# Showing model bias
model.network[0].bias

Parameter containing:
tensor([ 0.0118, -0.1106, -0.2905], requires_grad=True)

In [172]:
model.network[2].bias

Parameter containing:
tensor([0.4338], requires_grad=True)

In [173]:
# Visuualize
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

---
---