# **How Perceptrons Learn - Intuition, Code, and Edge Cases**

In [121]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

---
---

## **Perceptrons from scratch**

### **Main Implementation**

In [122]:
class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4
        print(f"Weights: \n{self.weights}\n")

        self.eta = eta
        self.epochs = epochs

    def activation_func(self, inputs, weights):
        z = np.dot(inputs, weights)
        return np.where(z<1, 0, 1)

    def fit(self, X, y):
        self.X = X
        self.y = y

        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}\n")

        for epoch in range(self.epochs):
            print((f"Epoch: {epoch}"))

            y_hat = self.activation_func(X_with_bias, self.weights)
            print((f"Predictions: \n{y_hat}"))

            error = self.y - y_hat
            print(f"Error: \n{error}")

            self.weights = self.weights + (self.eta * np.dot(X_with_bias.T, error))
            print(f"Updated weights: \n{self.weights}")

            print("#############\n")


    def predict(self, X):
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]

        return self.activation_func(X_with_bias, self.weights)

---

### **AND Gate**

In [123]:
AND = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1]
}

AND = pd.DataFrame(AND)
AND

,x1,x2,y
0,0,0,0
1,0,1,0
2,1,0,0
3,1,1,1


In [124]:
X = AND.drop("y", axis=1)
y = AND["y"]
y.to_frame()

,y
0,0
1,0
2,0
3,1


In [125]:
and_model = Perceptron(eta=0.5, epochs=10)
and_model.fit(X,y)

Weights: 
[1.30842408e-04 2.57088675e-06 7.91885158e-05]

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]

Epoch: 0
Predictions: 
[0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights: 
[ 0.50013084  0.50000257 -0.49992081]
#############

Epoch: 1
Predictions: 
[0 0 1 1]
Error: 
0    0
1    0
2   -1
3    0
Name: y, dtype: int64
Updated weights: 
[1.30842408e-04 5.00002571e-01 7.91885158e-05]
#############

Epoch: 2
Predictions: 
[0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights: 
[ 0.50013084  1.00000257 -0.49992081]
#############

Epoch: 3
Predictions: 
[0 1 1 1]
Error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights: 
[1.30842408e-04 5.00002571e-01 5.00079189e-01]
#############

Epoch: 4
Predictions: 
[0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights: 
[5.00130842e-01 1.00000257e+00 7.91885158e-05]
#############

Epoch: 5
Predictions: 
[0 0 0

---

### **OR Gate**

In [126]:
OR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,1]
}

OR = pd.DataFrame(OR)

X = OR.drop("y", axis=1)
y = OR["y"]
y.to_frame()

or_model = Perceptron(eta=0.5, epochs=10)
or_model.fit(X,y)

Weights: 
[6.18160874e-05 5.45235092e-06 1.03754014e-04]

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]

Epoch: 0
Predictions: 
[0 0 0 0]
Error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights: 
[ 1.00006182  1.00000545 -1.49989625]
#############

Epoch: 1
Predictions: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 2
Predictions: 
[0 1 1 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 3
Predictions: 
[0 1 1 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 4
Predictions: 
[0 1 1 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
[ 1.00006182  1.00000545 -0.99989625]
#############

Epoch: 5
Predictions: 
[0 1 1 1]
Error: 
0    0
1    0
2

---

### **XOR Gate**

In [127]:
XOR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,0]
}

XOR = pd.DataFrame(XOR)

X = XOR.drop("y", axis=1)
y = XOR["y"]
y.to_frame()

xor_model = Perceptron(eta=0.1, epochs=1000)
xor_model.fit(X,y)

Streaming output truncated to the last 5000 lines.
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: 
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 616
Predictions: 
[0 0 0 0]
Error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: 
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 617
Predictions: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: 
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 618
Predictions: 
[0 0 0 0]
Error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: 
[ 0.10021566  0.10003317 -1.00007203]
#############

Epoch: 619
Predictions: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: 
[ 2.15663705e-04  3.31682390e-05 -8.00072033e-01]
#############

Epoch: 620
Predictions: 
[0 0 0 0]
Error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: 
[ 0.10021566  0.10003317 -1.0000

---
---